/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_v1_auth_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Identity */
        get: operations["get_identity_api_v1_identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Status Endpoint */
        get: operations["get_device_status_endpoint_api_v1_status_device_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Port Status Endpoint */
        get: operations["get_port_status_endpoint_api_v1_status_ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Port Counters Endpoint */
        get: operations["get_port_counters_endpoint_api_v1_status_counters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/alert-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert Log Endpoint */
        get: operations["get_alert_log_endpoint_api_v1_status_alert_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backups */
        get: operations["list_backups_api_v1_backups_get"];
        put?: never;
        /** Create Backup */
        post: operations["create_backup_api_v1_backups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/live-sha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Sha */
        get: operations["get_live_sha_api_v1_backups_live_sha_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Backup */
        get: operations["download_backup_api_v1_backups__filename__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Backup */
        get: operations["diff_backup_api_v1_backups__filename__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Backup */
        post: operations["restore_backup_api_v1_backups__filename__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Backup */
        delete: operations["delete_backup_api_v1_backups__filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration Placeholder */
        get: operations["configuration_placeholder_api_v1_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security Placeholder */
        get: operations["security_placeholder_api_v1_security_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics Placeholder */
        get: operations["diagnostics_placeholder_api_v1_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Support Placeholder */
        get: operations["support_placeholder_api_v1_support_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertEvent
         * @description One row from the alert-log stream (/cgi/fflog?action=list).
         */
        AlertEvent: {
            /** Row Id */
            row_id: string;
            /** Alert Name */
            alert_name: string;
            /** Category */
            category: string;
            /** Ts Centiseconds */
            ts_centiseconds: number;
            /** Description */
            description: string;
        };
        /**
         * AlertLog
         * @description Parsed /cgi/fflog?action=list response.
         *
         *     Line 1 is a meta/cursor line; subsequent lines are alert rows.
         */
        AlertLog: {
            /** Latest Ts Centiseconds */
            latest_ts_centiseconds: number;
            /** Cursor Or Count */
            cursor_or_count: number;
            /** Events */
            events: components["schemas"]["AlertEvent"][];
        };
        /**
         * BackupMeta
         * @description Sidecar metadata describing a stored backup.
         */
        BackupMeta: {
            /** Filename */
            filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "pre-write" | "scheduled";
        };
        /** CreateBackupRequest */
        CreateBackupRequest: {
            /**
             * Trigger
             * @default manual
             * @enum {string}
             */
            trigger: "manual" | "pre-write" | "scheduled";
        };
        /**
         * DeviceIdentity
         * @description Parsed switch identity as rendered by /identity/identity.html.
         *
         *     All trailing whitespace the template emits in cells is stripped on parse.
         *     The `management_server_url` is `None` when the switch has no URL
         *     configured (the applet helper `link("")` renders "(None)" in that case).
         */
        DeviceIdentity: {
            /**
             * System Name
             * @description Hostname (identity.html:86).
             */
            system_name: string;
            /**
             * System Location
             * @description SNMP sysLocation.
             */
            system_location: string;
            /**
             * System Contact
             * @description SNMP sysContact.
             */
            system_contact: string;
            /**
             * Uptime Centiseconds
             * @description Hundredths of a second since boot; ft() divides by 100.
             */
            uptime_centiseconds: number;
            /**
             * Cpu Pct
             * @description System CPU utilisation %.
             */
            cpu_pct: number;
            /**
             * Memory Total Bytes
             * @description Total system memory (bytes).
             */
            memory_total_bytes: number;
            /**
             * Memory Free Bytes
             * @description Free system memory (bytes).
             */
            memory_free_bytes: number;
            /**
             * Product
             * @description e.g. 'ProCurve Switch 2810-24G (J9021A)'.
             */
            product: string;
            /**
             * Base Mac
             * @description Base MAC in canonical colon-separated uppercase.
             */
            base_mac: string;
            /**
             * Serial Number
             * @description Switch serial number.
             */
            serial_number: string;
            /**
             * Firmware Version
             * @description e.g. 'N.11.78, ROM N.10.01'.
             */
            firmware_version: string;
            /**
             * Ip Address
             * Format: ipv4
             * @description Management IPv4.
             */
            ip_address: string;
            /**
             * Management Server Url
             * @description URL rendered by link(); None when switch reports '(None)'.
             */
            management_server_url?: string | null;
        };
        /**
         * DeviceStatusBanner
         * @description Parsed /cgi/fflog?action=status response (first line only).
         *
         *     The applet reads exactly one line and tokenizes on `~` (positions 0..3).
         *     On this firmware the response body is identical to action=list, but the
         *     first line is a 2-field meta record — the applet ignores trailing lines.
         */
        DeviceStatusBanner: {
            /** State */
            state: string;
            /** Index */
            index?: string | null;
            /** Description */
            description?: string | null;
            /** Ts Centiseconds */
            ts_centiseconds?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unreachable";
            /** Switch Reachable */
            switch_reachable: boolean;
        };
        /** LiveShaResponse */
        LiveShaResponse: {
            /** Sha256 */
            sha256: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Session Id */
            session_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * PortCounters
         * @description One row from /cgi/portc.
         *
         *     Wire position 2 is the same hidden label cell shared with /cgi/get_ports
         *     (preserved as `port_type_label`). Counters are packet counts, not bytes,
         *     and wrap at 2^32 — callers computing deltas must tolerate wrap.
         */
        PortCounters: {
            /** Port */
            port: number;
            /** Port Name */
            port_name: string;
            /**
             * Port Type Label
             * @default
             */
            port_type_label: string;
            /** Mcast Rx */
            mcast_rx: number;
            /** Mcast Tx */
            mcast_tx: number;
            /** Bcast Rx */
            bcast_rx: number;
            /** Bcast Tx */
            bcast_tx: number;
            /** Pkts Rx */
            pkts_rx: number;
            /** Pkts Tx */
            pkts_tx: number;
            /** Errors Rx */
            errors_rx: number;
        };
        /** PortCountersList */
        PortCountersList: {
            /** Ports */
            ports: components["schemas"]["PortCounters"][];
        };
        /**
         * PortStatus
         * @description One row from /cgi/get_ports.
         *
         *     Wire has 10 fields but the GUI only renders 8 columns. Wire position 2
         *     is a hidden decorative label (single space for most ports; e.g. "UPS" on
         *     a labelled port) — preserved as `port_type_label`. Wire position 9 is a
         *     trailing integer always observed as `0` — preserved as `_extra` for
         *     round-trip fidelity; its purpose is unknown.
         */
        PortStatus: {
            /** Port */
            port: number;
            /** Port Name */
            port_name: string;
            /**
             * Port Type Label
             * @default
             */
            port_type_label: string;
            /** Port Type */
            port_type: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Link Status
             * @enum {string}
             */
            link_status: "Up" | "Down";
            /** Current Mode */
            current_mode: string;
            /**
             * Trunk
             * @default
             */
            trunk: string;
            /** Flow Ctrl */
            flow_ctrl: string;
            /**
             * Extra
             * @description Unknown trailing integer; observed 0.
             * @default 0
             */
            extra: number;
        };
        /** PortStatusList */
        PortStatusList: {
            /** Ports */
            ports: components["schemas"]["PortStatus"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhoamiResponse */
        WhoamiResponse: {
            /** Username */
            username: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    whoami_api_v1_auth_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
        };
    };
    get_identity_api_v1_identity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceIdentity"];
                };
            };
        };
    };
    get_device_status_endpoint_api_v1_status_device_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStatusBanner"];
                };
            };
        };
    };
    get_port_status_endpoint_api_v1_status_ports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortStatusList"];
                };
            };
        };
    };
    get_port_counters_endpoint_api_v1_status_counters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortCountersList"];
                };
            };
        };
    };
    get_alert_log_endpoint_api_v1_status_alert_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertLog"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    list_backups_api_v1_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupMeta"][];
                };
            };
        };
    };
    create_backup_api_v1_backups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateBackupRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_sha_api_v1_backups_live_sha_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveShaResponse"];
                };
            };
        };
    };
    download_backup_api_v1_backups__filename__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_backup_api_v1_backups__filename__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_backup_api_v1_backups__filename__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_backup_api_v1_backups__filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configuration_placeholder_api_v1_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    security_placeholder_api_v1_security_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    diagnostics_placeholder_api_v1_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    support_placeholder_api_v1_support_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
