/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_v1_auth_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Identity */
        get: operations["get_identity_api_v1_identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Status Endpoint */
        get: operations["get_device_status_endpoint_api_v1_status_device_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Port Status Endpoint */
        get: operations["get_port_status_endpoint_api_v1_status_ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Port Counters Endpoint */
        get: operations["get_port_counters_endpoint_api_v1_status_counters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/alert-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert Log Endpoint */
        get: operations["get_alert_log_endpoint_api_v1_status_alert_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backups */
        get: operations["list_backups_api_v1_backups_get"];
        put?: never;
        /** Create Backup */
        post: operations["create_backup_api_v1_backups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/live-sha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Sha */
        get: operations["get_live_sha_api_v1_backups_live_sha_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Backup */
        get: operations["download_backup_api_v1_backups__filename__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Backup */
        get: operations["diff_backup_api_v1_backups__filename__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Backup */
        post: operations["restore_backup_api_v1_backups__filename__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Backup */
        delete: operations["delete_backup_api_v1_backups__filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read System */
        get: operations["read_system_api_v1_configuration_system_get"];
        /**
         * Write System
         * @description Write system name / location / contact.
         *
         *     Not lockout-risky — the pre-write backup is sufficient rollback.
         */
        put: operations["write_system_api_v1_configuration_system_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Ip */
        get: operations["read_ip_api_v1_configuration_ip_get"];
        /**
         * Write Ip
         * @description Write the management-interface IP configuration.
         *
         *     LOCKOUT RISK: changing VLAN / mode / gateway on the management
         *     interface can sever the operator's TCP session to the switch
         *     instantly.  Gated with ``require_host_confirmation``.
         */
        put: operations["write_ip_api_v1_configuration_ip_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Ports
         * @description List every port's current configuration.
         */
        get: operations["read_ports_api_v1_configuration_ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/ports/{port}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Port Form
         * @description Fetch the edit-form state for a single port.
         *
         *     The underlying procurve op supports multi-port selection; Phase 3
         *     exposes single-port reads only. Multi-port bulk edits can be added
         *     later if the UI ever needs them.
         */
        get: operations["read_port_form_api_v1_configuration_ports__port__get"];
        /**
         * Write Port Config
         * @description Write per-port configuration (enable / name / speed / flow-control).
         *
         *     The URL ``{port}`` is authoritative: we rebuild the request so the
         *     path and body agree even if the caller submitted a stale body with
         *     ``request.ports`` targeting a different port. Not lockout-risky —
         *     the pre-write autobackup is sufficient rollback.
         */
        put: operations["write_port_config_api_v1_configuration_ports__port__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/gateway": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Write Gateway
         * @description Set only the default gateway.
         *
         *     A wrong gateway breaks external routing but the operator's direct
         *     LAN session to the switch survives — no host confirmation (see
         *     module docstring for the trade-off).
         */
        put: operations["write_gateway_api_v1_configuration_gateway_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/device-features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Device Features
         * @description Read IGMP / Spanning-Tree flags + VLAN count.
         */
        get: operations["read_device_features_api_v1_configuration_device_features_get"];
        /**
         * Write Device Features
         * @description Write IGMP / Spanning Tree flags. Not lockout-risky.
         */
        put: operations["write_device_features_api_v1_configuration_device_features_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/fault-detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Fault Detection
         * @description Read fault-detection sensitivity.
         */
        get: operations["read_fault_detection_api_v1_configuration_fault_detection_get"];
        /**
         * Write Fault Detection
         * @description Write fault-detection sensitivity (one of FaultSensitivity).
         */
        put: operations["write_fault_detection_api_v1_configuration_fault_detection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Monitor
         * @description Read port-mirroring state (enabled, candidate + selected dest port).
         */
        get: operations["read_monitor_api_v1_configuration_monitor_get"];
        /**
         * Write Monitor
         * @description Enable / disable port mirroring (dest + source mask required when on).
         */
        put: operations["write_monitor_api_v1_configuration_monitor_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuration/bob-ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Bob Ports
         * @description Device-view port rollup (admin status per port + link state).
         */
        get: operations["read_bob_ports_api_v1_configuration_bob_ports_get"];
        /**
         * Write Bob Ports
         * @description Bulk-enable / disable admin status on a set of ports.
         */
        put: operations["write_bob_ports_api_v1_configuration_bob_ports_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/web-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Web Access */
        get: operations["read_web_access_api_v1_security_web_access_get"];
        /**
         * Write Web Access
         * @description Configure the SSL subsystem (HTTPS on/off, port, cert mode).
         *
         *     LOCKOUT RISK: enabling HTTPS-only without a valid certificate
         *     installed will lock you out of the web UI. The browser will refuse
         *     to present the self-signed cert without an override, and the
         *     firmware does not fall back to HTTP while HTTPS is on. Keep an SSH
         *     session open before toggling this.
         */
        put: operations["write_web_access_api_v1_security_web_access_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/web-managers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Web Managers */
        get: operations["read_web_managers_api_v1_security_web_managers_get"];
        put?: never;
        /**
         * Write Web Managers
         * @description Add / replace / delete an authorized-manager IP entry.
         *
         *     LOCKOUT RISK: the Authorized-Manager list is a whitelist. Adding an
         *     entry that excludes your client IP (or deleting your own row) locks
         *     you out of the web UI immediately, with no graceful back-off.
         */
        post: operations["write_web_managers_api_v1_security_web_managers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/per-port": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Per Port */
        get: operations["read_per_port_api_v1_security_per_port_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/intrusion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Intrusion */
        get: operations["read_intrusion_api_v1_security_intrusion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/ssl-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Ssl State */
        get: operations["read_ssl_state_api_v1_security_ssl_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/per-port/{port}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Write Per Port
         * @description Configure one port's security policy.
         *
         *     Not lockout-risky — the pre-write backup is sufficient rollback.
         *     The path param ``port`` must match ``body.request.port``; a mismatch
         *     is a client-side mistake and we do not silently coerce it.
         */
        put: operations["write_per_port_api_v1_security_per_port__port__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/intrusion/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write Intrusion Reset
         * @description Clear cosmetic intrusion alert flags. Low risk — still autobacked.
         */
        post: operations["write_intrusion_reset_api_v1_security_intrusion_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Ping */
        post: operations["run_ping_api_v1_diagnostics_ping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/link-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Link Test */
        post: operations["run_link_test_api_v1_diagnostics_link_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/configuration-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration Report */
        get: operations["configuration_report_api_v1_diagnostics_configuration_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/device-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Device */
        post: operations["reset_device_api_v1_diagnostics_device_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Support
         * @description Return the static Support-tab info. No switch I/O.
         */
        get: operations["get_support_api_v1_support_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessLevel
         * @enum {string}
         */
        AccessLevel: "Manager" | "Operator";
        /**
         * AccessLevelCode
         * @description Wire codes for access level (inverse of the read-side string enum).
         * @enum {integer}
         */
        AccessLevelCode: 1 | 2;
        /**
         * AddWebManagerRequest
         * @description Add a new authorized-manager IP entry (`action=1` variant).
         *
         *     `indeces` defaults to an empty list (serialized as `indeces=` on the wire)
         *     because the add-action CGI assigns the index server-side. Replace and
         *     delete variants require a non-empty `indeces` because they operate on
         *     existing rows identified by index.
         */
        AddWebManagerRequest: {
            /**
             * Action
             * @default 1
             * @constant
             */
            action: 1;
            /**
             * Ip
             * Format: ipv4
             */
            ip: string;
            /**
             * Mask
             * Format: ipv4
             * @default 255.255.255.255
             */
            mask: string;
            level: components["schemas"]["AccessLevelCode"];
            /** Indeces */
            indeces?: number[];
        };
        /**
         * AddressSelection
         * @description Address-selection display tokens from `/cgi/perports`.
         * @enum {string}
         */
        AddressSelection: "Continuous" | "Static" | "Port Access" | "Limited";
        /**
         * AlertEvent
         * @description One row from the alert-log stream (/cgi/fflog?action=list).
         */
        AlertEvent: {
            /** Row Id */
            row_id: string;
            /** Alert Name */
            alert_name: string;
            /** Category */
            category: string;
            /** Ts Centiseconds */
            ts_centiseconds: number;
            /** Description */
            description: string;
        };
        /**
         * AlertLog
         * @description Parsed /cgi/fflog?action=list response.
         *
         *     Line 1 is a meta/cursor line; subsequent lines are alert rows.
         */
        AlertLog: {
            /** Latest Ts Centiseconds */
            latest_ts_centiseconds: number;
            /** Cursor Or Count */
            cursor_or_count: number;
            /** Events */
            events: components["schemas"]["AlertEvent"][];
        };
        /**
         * AuthorizedManager
         * @description One row from `/cgi/webMgr`.
         */
        AuthorizedManager: {
            /** Index */
            index: number;
            /**
             * Ip
             * Format: ipv4
             */
            ip: string;
            /**
             * Mask
             * Format: ipv4
             */
            mask: string;
            access_level: components["schemas"]["AccessLevel"];
        };
        /**
         * BackupMeta
         * @description Sidecar metadata describing a stored backup.
         */
        BackupMeta: {
            /** Filename */
            filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "pre-write" | "scheduled";
        };
        /**
         * BobDevice
         * @description First line of /cgi/get_bobports — switch chassis metadata.
         */
        BobDevice: {
            /** Codename */
            codename: string;
            /** Port Count */
            port_count: number;
        };
        /**
         * BobPort
         * @description One port line from /cgi/get_bobports.
         *
         *     `label` is the rendered label the applet shows under the port — it may
         *     differ from the SNMP port name. `mode` and `poe` are optional (many
         *     firmwares omit the trailing fields).
         */
        BobPort: {
            /** Port */
            port: number;
            /** Kind */
            kind: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Link */
            link: boolean;
            /** Enabled */
            enabled: boolean;
            /** Mode */
            mode?: string | null;
            /** Poe */
            poe?: number | null;
        };
        /**
         * BobPortsResponse
         * @description Device + port rollup for /cgi/get_bobports.
         */
        BobPortsResponse: {
            device: components["schemas"]["BobDevice"];
            /** Ports */
            ports?: components["schemas"]["BobPort"][];
        };
        /**
         * CertMode
         * @description Certificate-mode radio state from `ssl_cert.html`.
         * @enum {integer}
         */
        CertMode: 1 | 2;
        /**
         * CertType
         * @description `certtype` wire codes.
         * @enum {integer}
         */
        CertType: 3 | 4;
        /**
         * CertificMode
         * @description `certific` wire codes (assembled by submitApply() JS helper).
         * @enum {integer}
         */
        CertificMode: 2 | 3;
        /**
         * ConfigWriteAck
         * @description Shared ack type for write endpoints whose response body is unverified.
         */
        ConfigWriteAck: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Raw Body */
            raw_body?: string | null;
        };
        /**
         * ConfigurationReportResponse
         * @description Trimmed view of :class:`procurve_client.models.diagnostics.ConfigurationReport`.
         *
         *     The full model carries a ``running_config`` dataclass for the structured
         *     parse; the Diagnostics tab only needs the rendered text + raw HTML, so we
         *     return a flat Pydantic model here to keep the OpenAPI schema clean.
         */
        ConfigurationReportResponse: {
            /** Raw Html */
            raw_html: string;
            /** Config Text */
            config_text: string;
        };
        /** CreateBackupRequest */
        CreateBackupRequest: {
            /**
             * Trigger
             * @default manual
             * @enum {string}
             */
            trigger: "manual" | "pre-write" | "scheduled";
        };
        /**
         * DeleteWebManagerRequest
         * @description `action=3` variant — delete the entry at `indeces[0]`.
         */
        DeleteWebManagerRequest: {
            /**
             * Action
             * @default 3
             * @constant
             */
            action: 3;
            /** Indeces */
            indeces: number[];
        };
        /**
         * DeviceFeaturesPage
         * @description Scraped state from /configuration/features2*.html.
         *
         *     `igmp` and `spanning_tree` are `None` when the injected JS variable was
         *     `Invalid OID` (page-generator quirk on multi-VLAN variants).
         */
        DeviceFeaturesPage: {
            /** Vlan Count */
            vlan_count: number;
            /**
             * Crip Stat
             * @default 0
             */
            crip_stat: string;
            /** Igmp */
            igmp?: boolean | null;
            /** Spanning Tree */
            spanning_tree?: boolean | null;
        };
        /**
         * DeviceIdentity
         * @description Parsed switch identity as rendered by /identity/identity.html.
         *
         *     All trailing whitespace the template emits in cells is stripped on parse.
         *     The `management_server_url` is `None` when the switch has no URL
         *     configured (the applet helper `link("")` renders "(None)" in that case).
         */
        DeviceIdentity: {
            /**
             * System Name
             * @description Hostname (identity.html:86).
             */
            system_name: string;
            /**
             * System Location
             * @description SNMP sysLocation.
             */
            system_location: string;
            /**
             * System Contact
             * @description SNMP sysContact.
             */
            system_contact: string;
            /**
             * Uptime Centiseconds
             * @description Hundredths of a second since boot; ft() divides by 100.
             */
            uptime_centiseconds: number;
            /**
             * Cpu Pct
             * @description System CPU utilisation %.
             */
            cpu_pct: number;
            /**
             * Memory Total Bytes
             * @description Total system memory (bytes).
             */
            memory_total_bytes: number;
            /**
             * Memory Free Bytes
             * @description Free system memory (bytes).
             */
            memory_free_bytes: number;
            /**
             * Product
             * @description e.g. 'ProCurve Switch 2810-24G (J9021A)'.
             */
            product: string;
            /**
             * Base Mac
             * @description Base MAC in canonical colon-separated uppercase.
             */
            base_mac: string;
            /**
             * Serial Number
             * @description Switch serial number.
             */
            serial_number: string;
            /**
             * Firmware Version
             * @description e.g. 'N.11.78, ROM N.10.01'.
             */
            firmware_version: string;
            /**
             * Ip Address
             * Format: ipv4
             * @description Management IPv4.
             */
            ip_address: string;
            /**
             * Management Server Url
             * @description URL rendered by link(); None when switch reports '(None)'.
             */
            management_server_url?: string | null;
        };
        /**
         * DeviceResetRequest
         * @description Reboot confirmation. `confirm_switch_host` must equal settings.switch_host.
         */
        DeviceResetRequest: {
            /** Confirm Switch Host */
            confirm_switch_host: string;
        };
        /**
         * DeviceResetResponse
         * @description Outcome of /cgi/device_reset (FORBIDDEN — see module docstring).
         */
        DeviceResetResponse: {
            /**
             * Initiated
             * @default false
             */
            initiated: boolean;
            /** Message */
            message?: string | null;
        };
        /**
         * DeviceStatusBanner
         * @description Parsed /cgi/fflog?action=status response (first line only).
         *
         *     The applet reads exactly one line and tokenizes on `~` (positions 0..3).
         *     On this firmware the response body is identical to action=list, but the
         *     first line is a 2-field meta record — the applet ignores trailing lines.
         */
        DeviceStatusBanner: {
            /** State */
            state: string;
            /** Index */
            index?: string | null;
            /** Description */
            description?: string | null;
            /** Ts Centiseconds */
            ts_centiseconds?: number | null;
        };
        /**
         * FaultDetectionPage
         * @description Scraped state from /configuration/web_agent.html.
         */
        FaultDetectionPage: {
            sensitivity: components["schemas"]["FaultSensitivity"];
            /** Dps */
            dps?: number | null;
        };
        /**
         * FaultSensitivity
         * @enum {integer}
         */
        FaultSensitivity: 0 | 32 | 128 | 224;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unreachable";
            /** Switch Reachable */
            switch_reachable: boolean;
        };
        /**
         * IntrusionEntry
         * @description One row from `/cgi/intrusion`.
         */
        IntrusionEntry: {
            /** Port */
            port: number;
            /** Port Name */
            port_name: string;
            /** Intruder Address */
            intruder_address: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * IntrusionLogResponse
         * @description Parsed shape of `/cgi/intrusion` (read).
         */
        IntrusionLogResponse: {
            /** Entries */
            entries?: components["schemas"]["IntrusionEntry"][];
        };
        /**
         * IpConfigPage
         * @description Scraped state from /configuration/ip1.html + /configuration/ip2.html.
         *
         *     `ip_address` / `subnet_mask` are injected plain-text on ip2.html and are
         *     read-only on this firmware — they are not editable via the web UI.
         */
        IpConfigPage: {
            /** Vlan Id */
            vlan_id: number;
            mode: components["schemas"]["IpMode"];
            /** Ip Address */
            ip_address?: string | null;
            /** Subnet Mask */
            subnet_mask?: string | null;
            /**
             * Gateway
             * Format: ipv4
             */
            gateway: string;
        };
        /**
         * IpMode
         * @enum {integer}
         */
        IpMode: 1 | 2 | 3;
        /**
         * LinkTestRequest
         * @description L2 link test. `destination` is a MAC address (dash- or colon-separated).
         */
        LinkTestRequest: {
            /** Destination */
            destination: string;
            /**
             * Packet Count
             * @default 10
             */
            packet_count: number;
            /**
             * Timeout S
             * @default 5
             */
            timeout_s: number;
        };
        /** LiveShaResponse */
        LiveShaResponse: {
            /** Sha256 */
            sha256: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Session Id */
            session_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * MonitorPage
         * @description Scraped state from /configuration/monitor1.html.
         */
        MonitorPage: {
            /** Enabled */
            enabled: boolean;
            /** Candidate Dest Ports */
            candidate_dest_ports?: number[];
            /** Selected Dest Port */
            selected_dest_port?: number | null;
        };
        /**
         * PerportsResponse
         * @description Parsed shape of `/cgi/perports?GR=<group>`.
         */
        PerportsResponse: {
            /** Rows */
            rows?: components["schemas"]["PortSecurityRow"][];
        };
        /**
         * PingRequest
         * @description Ping test. `destination` is an IPv4 address or hostname.
         */
        PingRequest: {
            /** Destination */
            destination: string;
            /**
             * Packet Count
             * @default 10
             */
            packet_count: number;
            /**
             * Timeout S
             * @default 5
             */
            timeout_s: number;
        };
        /**
         * PingResult
         * @description Parsed result of /cgi/ping (for both ping and link_test).
         *
         *     The switch returns HTML containing `Successes: <N>` / `Failures: <N>`
         *     plus a row of LED images. Parse the two counters; preserve the raw HTML
         *     so the UI can render the LEDs later if desired.
         */
        PingResult: {
            /** Successes */
            successes: number;
            /** Failures */
            failures: number;
            /** Raw Html */
            raw_html: string;
        };
        /**
         * PortConfig
         * @description One row from /cgi/get_portscfg (the Configuration tab's Ports list).
         *
         *     Structurally near-identical to `PortStatus` but semantically different:
         *     position 5 is `config_status` (`.` = nothing to report) and position 6
         *     is the *configured* mode, not the current negotiated one.
         */
        PortConfig: {
            /** Port */
            port: number;
            /** Port Name */
            port_name: string;
            /**
             * Port Type Label
             * @default
             */
            port_type_label: string;
            /** Port Type */
            port_type: string;
            /** Enabled */
            enabled: boolean;
            /** Config Status */
            config_status: string;
            /** Config Mode */
            config_mode: string;
            /**
             * Trunk
             * @default
             */
            trunk: string;
            /** Flow Control */
            flow_control: boolean;
            /**
             * Extra
             * @description Wire position 9; observed 0. Unknown.
             * @default 0
             */
            extra: number;
        };
        /** PortConfigList */
        PortConfigList: {
            /** Ports */
            ports: components["schemas"]["PortConfig"][];
        };
        /**
         * PortCounters
         * @description One row from /cgi/portc.
         *
         *     Wire position 2 is the same hidden label cell shared with /cgi/get_ports
         *     (preserved as `port_type_label`). Counters are packet counts, not bytes,
         *     and wrap at 2^32 — callers computing deltas must tolerate wrap.
         */
        PortCounters: {
            /** Port */
            port: number;
            /** Port Name */
            port_name: string;
            /**
             * Port Type Label
             * @default
             */
            port_type_label: string;
            /** Mcast Rx */
            mcast_rx: number;
            /** Mcast Tx */
            mcast_tx: number;
            /** Bcast Rx */
            bcast_rx: number;
            /** Bcast Tx */
            bcast_tx: number;
            /** Pkts Rx */
            pkts_rx: number;
            /** Pkts Tx */
            pkts_tx: number;
            /** Errors Rx */
            errors_rx: number;
        };
        /** PortCountersList */
        PortCountersList: {
            /** Ports */
            ports: components["schemas"]["PortCounters"][];
        };
        /**
         * PortForm
         * @description Parsed result of /cgi/port_form?indeces=... — the per-port edit form.
         *
         *     `port_name` may be `""` when a single port is selected and has no name;
         *     on multi-port selects where ports disagree it is empty too (the live UI
         *     would render it as "differs across selection").
         */
        PortForm: {
            /** Ports */
            ports: number[];
            /**
             * Port Name
             * @default
             */
            port_name: string;
            /** Admin Enabled */
            admin_enabled: boolean;
            mode: components["schemas"]["PortMode"];
            /** Flow Control Enabled */
            flow_control_enabled: boolean;
        };
        /**
         * PortMode
         * @description Values from the <select name=hpSwitchPortFastEtherMode> on port_form.
         *
         *     Value `6` is unused (a legacy auto mode removed in this firmware).
         * @enum {integer}
         */
        PortMode: 1 | 2 | 3 | 4 | 5 | 7 | 8 | 9 | 11;
        /**
         * PortSecurityMode
         * @description Values from `<select name=mode>` on `perport_form1.html`.
         *
         *     # TODO: needs live capture — values 3/4 (if present) are unknown.
         * @enum {integer}
         */
        PortSecurityMode: 1 | 2 | 5;
        /**
         * PortSecurityRow
         * @description One row from `/cgi/perports?GR=`.
         *
         *     Blank-string columns are serialized as a literal single space by
         *     the switch to preserve column alignment in the applet renderer;
         *     we pass them through unchanged.
         */
        PortSecurityRow: {
            /** Port */
            port: number;
            /** Port Label */
            port_label: string;
            /** Port Name */
            port_name: string;
            address_selection: components["schemas"]["AddressSelection"];
            /** Authorized Address */
            authorized_address: string;
            /** Mode */
            mode: string;
            /** Security Action */
            security_action: number;
            /** Address Limit */
            address_limit: number;
            /** Trunk */
            trunk: boolean;
        };
        /**
         * PortStatus
         * @description One row from /cgi/get_ports.
         *
         *     Wire has 10 fields but the GUI only renders 8 columns. Wire position 2
         *     is a hidden decorative label (single space for most ports; e.g. "UPS" on
         *     a labelled port) — preserved as `port_type_label`. Wire position 9 is a
         *     trailing integer always observed as `0` — preserved as `_extra` for
         *     round-trip fidelity; its purpose is unknown.
         */
        PortStatus: {
            /** Port */
            port: number;
            /** Port Name */
            port_name: string;
            /**
             * Port Type Label
             * @default
             */
            port_type_label: string;
            /** Port Type */
            port_type: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Link Status
             * @enum {string}
             */
            link_status: "Up" | "Down";
            /** Current Mode */
            current_mode: string;
            /**
             * Trunk
             * @default
             */
            trunk: string;
            /** Flow Ctrl */
            flow_ctrl: string;
            /**
             * Extra
             * @description Unknown trailing integer; observed 0.
             * @default 0
             */
            extra: number;
        };
        /** PortStatusList */
        PortStatusList: {
            /** Ports */
            ports: components["schemas"]["PortStatus"][];
        };
        /**
         * RSAKey
         * @description `rsakey` wire codes — corresponds to the RSA-key select widget.
         * @enum {integer}
         */
        RSAKey: 1 | 2 | 3 | 4;
        /**
         * ReplaceWebManagerRequest
         * @description `action=2` variant — modify the entry at `indeces[0]` in place.
         */
        ReplaceWebManagerRequest: {
            /**
             * Action
             * @default 2
             * @constant
             */
            action: 2;
            /**
             * Ip
             * Format: ipv4
             */
            ip: string;
            /**
             * Mask
             * Format: ipv4
             * @default 255.255.255.255
             */
            mask: string;
            level: components["schemas"]["AccessLevelCode"];
            /** Indeces */
            indeces: number[];
        };
        /**
         * ResetIntrusionFlagsResponse
         * @description Return shape for `/cgi/intrusion_clear`.
         */
        ResetIntrusionFlagsResponse: {
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /** Raw Body */
            raw_body?: string | null;
        };
        /**
         * SSLActionCode
         * @description Power state mirror for `action` on `/cgi/setssl`.
         * @enum {integer}
         */
        SSLActionCode: 1 | 2;
        /**
         * SSLState
         * @description Consolidated projection across ssl_config.html, ssl_cert.html,
         *     and ssl_menu.html.
         *
         *     `ssl_enabled` maps from the firmware's `sslStatus` (`1`=Off, `2`=On).
         *     `ca_signed_installed` maps from `crtStat` (`1`=not installed,
         *     `2`=installed).
         */
        SSLState: {
            /** Ssl Enabled */
            ssl_enabled: boolean;
            /**
             * Ssl Port
             * @default 443
             */
            ssl_port: number;
            cert_mode: components["schemas"]["CertMode"];
            /** Ca Signed Installed */
            ca_signed_installed: boolean;
        };
        /**
         * SecurityActionCode
         * @description Security-action codes.
         *
         *     # TODO: needs live capture — values 2/3 are inferred from the HTML
         *     label order and not confirmed against the switch.
         * @enum {integer}
         */
        SecurityActionCode: 1 | 2 | 3;
        /**
         * SetBobPortsBody
         * @description Body for ``PUT /api/v1/configuration/bob-ports``.
         */
        SetBobPortsBody: {
            request: components["schemas"]["SetBobPortsRequest"];
        };
        /**
         * SetBobPortsRequest
         * @description Parameters for /cgi/set_bobports (the bulk enable/disable button).
         *
         *     Wire uses `ifAdminStatus=1` for enable, `=2` for disable; port list goes
         *     into `indeces=<csv>` (note the misspelling — preserved on the wire).
         */
        SetBobPortsRequest: {
            /** Enable */
            enable: boolean;
            /** Ports */
            ports: number[];
        };
        /**
         * SetDefaultGatewayBody
         * @description Body for ``PUT /api/v1/configuration/gateway``.
         *
         *     No host confirmation — see module docstring for the trade-off.
         */
        SetDefaultGatewayBody: {
            request: components["schemas"]["SetDefaultGatewayRequest"];
        };
        /** SetDefaultGatewayRequest */
        SetDefaultGatewayRequest: {
            /**
             * Gateway
             * Format: ipv4
             */
            gateway: string;
        };
        /**
         * SetDeviceFeaturesBody
         * @description Body for ``PUT /api/v1/configuration/device-features``.
         */
        SetDeviceFeaturesBody: {
            request: components["schemas"]["SetDeviceFeaturesRequest"];
        };
        /**
         * SetDeviceFeaturesRequest
         * @description Write request for one of the five feature-set endpoints.
         *
         *     Use `endpoint` to pick the correct wire path. `igmp` / `spanning_tree`
         *     may be None to omit the corresponding field.
         */
        SetDeviceFeaturesRequest: {
            /**
             * Endpoint
             * @default /cgi/feature_set
             * @enum {string}
             */
            endpoint: "/cgi/feature_set" | "/cgi/feature2_set" | "/cgi/globalfeature_set" | "/cgi/vlanfeature_set" | "/cgi/vlan2feature_set";
            /**
             * Vlan Id
             * @default 1
             */
            vlan_id: number;
            /** Igmp */
            igmp?: boolean | null;
            /** Spanning Tree */
            spanning_tree?: boolean | null;
        };
        /**
         * SetFaultDetectionBody
         * @description Body for ``PUT /api/v1/configuration/fault-detection``.
         */
        SetFaultDetectionBody: {
            request: components["schemas"]["SetFaultDetectionRequest"];
        };
        /** SetFaultDetectionRequest */
        SetFaultDetectionRequest: {
            sensitivity: components["schemas"]["FaultSensitivity"];
        };
        /**
         * SetIpConfigBody
         * @description Body for ``PUT /api/v1/configuration/ip``.
         *
         *     ``request`` carries the full :class:`SetIpConfigRequest` the procurve op
         *     expects; ``confirm_switch_host`` gates against accidentally severing the
         *     operator's session to the switch.
         */
        SetIpConfigBody: {
            request: components["schemas"]["SetIpConfigRequest"];
            /** Confirm Switch Host */
            confirm_switch_host: string;
        };
        /** SetIpConfigRequest */
        SetIpConfigRequest: {
            /**
             * Gateway
             * Format: ipv4
             */
            gateway: string;
            /** Vlan Id */
            vlan_id: number;
            mode: components["schemas"]["IpMode"];
        };
        /**
         * SetMonitorBody
         * @description Body for ``PUT /api/v1/configuration/monitor``.
         */
        SetMonitorBody: {
            request: components["schemas"]["SetMonitorRequest"];
        };
        /** SetMonitorRequest */
        SetMonitorRequest: {
            /** Enabled */
            enabled: boolean;
            /** Dest Port */
            dest_port?: number | null;
            /** Source Mask */
            source_mask?: number | null;
        };
        /**
         * SetPerportBody
         * @description Body for ``PUT /api/v1/security/per-port/{port}``.
         *
         *     No host confirmation — per-port security tweaks are reversible via the
         *     pre-write backup and are not lockout-risky.
         */
        SetPerportBody: {
            request: components["schemas"]["SetPerportRequest"];
        };
        /**
         * SetPerportRequest
         * @description Arguments for `/cgi/perport` — configure one port's security policy.
         */
        SetPerportRequest: {
            /**
             * Group
             * @default
             */
            group: string;
            /**
             * Trunk
             * @default 0
             */
            trunk: number;
            /** Port */
            port: number;
            /** Indeces */
            indeces: number[];
            mode: components["schemas"]["PortSecurityMode"];
            /** @default 1 */
            security_action: components["schemas"]["SecurityActionCode"];
            /**
             * Address Limit
             * @default 1
             */
            address_limit: number;
        };
        /**
         * SetPerportResponse
         * @description Return shape for `/cgi/perport` (write path).
         */
        SetPerportResponse: {
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /** Message */
            message?: string | null;
            /** Raw Body */
            raw_body?: string | null;
        };
        /**
         * SetPortConfigBody
         * @description Body for ``PUT /api/v1/configuration/ports/{port}``.
         *
         *     No ``confirm_switch_host`` — per-port tweaks are reversible via the
         *     pre-write autobackup and are not lockout-risky. The route handler
         *     rebuilds ``request.ports`` from the path ``{port}`` to prevent a stale
         *     body targeting the wrong port; the body's ``ports`` field is ignored
         *     in favour of the URL.
         */
        SetPortConfigBody: {
            request: components["schemas"]["SetPortConfigRequest"];
        };
        /**
         * SetPortConfigRequest
         * @description Parameters for /cgi/mod_ports.
         */
        SetPortConfigRequest: {
            /** Ports */
            ports: number[];
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Admin Enabled
             * @default true
             */
            admin_enabled: boolean;
            /** @default 9 */
            mode: components["schemas"]["PortMode"];
            /**
             * Flow Control Enabled
             * @default true
             */
            flow_control_enabled: boolean;
        };
        /**
         * SetSSLBody
         * @description Body for ``PUT /api/v1/security/web-access``.
         *
         *     ``request`` is the full :class:`SetSSLRequest` the procurve op expects;
         *     ``confirm_switch_host`` gates against accidental HTTPS-only lockouts.
         */
        SetSSLBody: {
            request: components["schemas"]["SetSSLRequest"];
            /** Confirm Switch Host */
            confirm_switch_host: string;
        };
        /**
         * SetSSLRequest
         * @description Arguments for the FORBIDDEN `/cgi/setssl` GET.
         *
         *     Top three fields (`enabled`, `port`, `cert_mode`) are always emitted.
         *     Certificate-creation fields are emitted only when `cert_mode` ==
         *     CREATE_OR_SELF_SIGNED AND `enabled` == ON, matching the JS helper
         *     that assembles the URL in `ssl_cert1.html:submitApply()`.
         *
         *     # TODO: needs live capture — the full param set beyond (action, prt,
         *     certific) is inferred from the HTML form names; the JS that appends
         *     them to the URL was truncated in the mirrored source.
         */
        SetSSLRequest: {
            /** @default 2 */
            enabled: components["schemas"]["SSLActionCode"];
            /**
             * Port
             * @default 443
             */
            port: number;
            /** @default 2 */
            cert_mode: components["schemas"]["CertificMode"];
            cert_type?: components["schemas"]["CertType"] | null;
            rsa_key?: components["schemas"]["RSAKey"] | null;
            /** Validity Start */
            validity_start?: string | null;
            /** Validity End */
            validity_end?: string | null;
            /** Common Name */
            common_name?: string | null;
            /** Organization Name */
            organization_name?: string | null;
            /** Organization Unit */
            organization_unit?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Country */
            country?: string | null;
        };
        /**
         * SetSSLResponse
         * @description Return shape for `/cgi/setssl` (write path).
         */
        SetSSLResponse: {
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /** Message */
            message?: string | null;
            /** Raw Body */
            raw_body?: string | null;
        };
        /**
         * SetSystemInfoBody
         * @description Body for ``PUT /api/v1/configuration/system``.
         *
         *     No ``confirm_switch_host`` — SNMP name / location / contact are not
         *     lockout-risky.
         */
        SetSystemInfoBody: {
            request: components["schemas"]["SetSystemInfoRequest"];
        };
        /** SetSystemInfoRequest */
        SetSystemInfoRequest: {
            /** Name */
            name: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Contact
             * @default
             */
            contact: string;
        };
        /**
         * SetWebManagerBody
         * @description Body for ``POST /api/v1/security/web-managers``.
         *
         *     ``request`` is the add/replace/delete discriminated union;
         *     ``confirm_switch_host`` gates against accidental management-IP lockouts.
         */
        SetWebManagerBody: {
            /** Request */
            request: components["schemas"]["AddWebManagerRequest"] | components["schemas"]["ReplaceWebManagerRequest"] | components["schemas"]["DeleteWebManagerRequest"];
            /** Confirm Switch Host */
            confirm_switch_host: string;
        };
        /**
         * SetWebManagerResponse
         * @description Return shape for `/cgi/webMgr` (write path).
         */
        SetWebManagerResponse: {
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /** Message */
            message?: string | null;
            /** Raw Body */
            raw_body?: string | null;
        };
        /**
         * SupportInfo
         * @description The static support-link info that replaces the old Support tab.
         *
         *     The legacy URL is preserved for parity; `current_url` is the modern
         *     replacement the new UI should actually link to. `available` is False
         *     because the original procurve.com domain no longer resolves.
         */
        SupportInfo: {
            /**
             * Legacy Url
             * @description The URL the Java applet's frameset originally loaded.
             * @default http://www.procurve.com
             */
            legacy_url: string;
            /**
             * Current Url
             * @description Suggested modern replacement (HPE Networking portal).
             * @default https://www.hpe.com/us/en/networking.html
             */
            current_url: string;
            /**
             * Available
             * @description False — the legacy procurve.com URL no longer resolves.
             * @default false
             */
            available: boolean;
            /**
             * Note
             * @default The legacy Support tab redirected to http://www.procurve.com, which is unreachable in 2026. Use `current_url` instead.
             */
            note: string;
        };
        /**
         * SystemInfoPage
         * @description Scraped state from /configuration/system.html.
         */
        SystemInfoPage: {
            /** Mac Address */
            mac_address: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Contact */
            contact: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WebAccessPage
         * @description Scraped projection of the device-passwords HTML form.
         *
         *     The firmware renders both username fields with empty `value=""`
         *     regardless of the configured usernames (standard password-form
         *     security hygiene). Reading the current values requires parsing
         *     `running-config` from `/cgi/configfile` instead.
         */
        WebAccessPage: {
            /**
             * Operator Username
             * @default
             */
            operator_username: string;
            /**
             * Manager Username
             * @default
             */
            manager_username: string;
        };
        /**
         * WebManagersResponse
         * @description Parsed shape of `/cgi/webMgr` (read).
         */
        WebManagersResponse: {
            /** Entries */
            entries?: components["schemas"]["AuthorizedManager"][];
        };
        /** WhoamiResponse */
        WhoamiResponse: {
            /** Username */
            username: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    whoami_api_v1_auth_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
        };
    };
    get_identity_api_v1_identity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceIdentity"];
                };
            };
        };
    };
    get_device_status_endpoint_api_v1_status_device_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStatusBanner"];
                };
            };
        };
    };
    get_port_status_endpoint_api_v1_status_ports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortStatusList"];
                };
            };
        };
    };
    get_port_counters_endpoint_api_v1_status_counters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortCountersList"];
                };
            };
        };
    };
    get_alert_log_endpoint_api_v1_status_alert_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertLog"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    list_backups_api_v1_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupMeta"][];
                };
            };
        };
    };
    create_backup_api_v1_backups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateBackupRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_sha_api_v1_backups_live_sha_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveShaResponse"];
                };
            };
        };
    };
    download_backup_api_v1_backups__filename__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_backup_api_v1_backups__filename__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_backup_api_v1_backups__filename__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_backup_api_v1_backups__filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_system_api_v1_configuration_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoPage"];
                };
            };
        };
    };
    write_system_api_v1_configuration_system_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSystemInfoBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_ip_api_v1_configuration_ip_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpConfigPage"];
                };
            };
        };
    };
    write_ip_api_v1_configuration_ip_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIpConfigBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_ports_api_v1_configuration_ports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortConfigList"];
                };
            };
        };
    };
    read_port_form_api_v1_configuration_ports__port__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortForm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_port_config_api_v1_configuration_ports__port__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPortConfigBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_gateway_api_v1_configuration_gateway_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDefaultGatewayBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_device_features_api_v1_configuration_device_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceFeaturesPage"];
                };
            };
        };
    };
    write_device_features_api_v1_configuration_device_features_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDeviceFeaturesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_fault_detection_api_v1_configuration_fault_detection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultDetectionPage"];
                };
            };
        };
    };
    write_fault_detection_api_v1_configuration_fault_detection_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetFaultDetectionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_monitor_api_v1_configuration_monitor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPage"];
                };
            };
        };
    };
    write_monitor_api_v1_configuration_monitor_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMonitorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_bob_ports_api_v1_configuration_bob_ports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BobPortsResponse"];
                };
            };
        };
    };
    write_bob_ports_api_v1_configuration_bob_ports_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBobPortsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigWriteAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_web_access_api_v1_security_web_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebAccessPage"];
                };
            };
        };
    };
    write_web_access_api_v1_security_web_access_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSSLBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetSSLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_web_managers_api_v1_security_web_managers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebManagersResponse"];
                };
            };
        };
    };
    write_web_managers_api_v1_security_web_managers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWebManagerBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetWebManagerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_per_port_api_v1_security_per_port_get: {
        parameters: {
            query?: {
                group?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerportsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_intrusion_api_v1_security_intrusion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntrusionLogResponse"];
                };
            };
        };
    };
    read_ssl_state_api_v1_security_ssl_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SSLState"];
                };
            };
        };
    };
    write_per_port_api_v1_security_per_port__port__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPerportBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPerportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_intrusion_reset_api_v1_security_intrusion_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetIntrusionFlagsResponse"];
                };
            };
        };
    };
    run_ping_api_v1_diagnostics_ping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_link_test_api_v1_diagnostics_link_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configuration_report_api_v1_diagnostics_configuration_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationReportResponse"];
                };
            };
        };
    };
    reset_device_api_v1_diagnostics_device_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_support_api_v1_support_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportInfo"];
                };
            };
        };
    };
}
