/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedVlansRouteImport } from './routes/_authenticated.vlans'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated.support'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated.status'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated.security'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated.diagnostics'
import { Route as AuthenticatedConfigurationRouteImport } from './routes/_authenticated.configuration'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated.backups'
import { Route as AuthenticatedStatusPortsPortRouteImport } from './routes/_authenticated.status.ports.$port'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVlansRoute = AuthenticatedVlansRouteImport.update({
  id: '/vlans',
  path: '/vlans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigurationRoute =
  AuthenticatedConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatusPortsPortRoute =
  AuthenticatedStatusPortsPortRouteImport.update({
    id: '/ports/$port',
    path: '/ports/$port',
    getParentRoute: () => AuthenticatedStatusRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/configuration': typeof AuthenticatedConfigurationRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/status': typeof AuthenticatedStatusRouteWithChildren
  '/support': typeof AuthenticatedSupportRoute
  '/vlans': typeof AuthenticatedVlansRoute
  '/status/ports/$port': typeof AuthenticatedStatusPortsPortRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/configuration': typeof AuthenticatedConfigurationRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/status': typeof AuthenticatedStatusRouteWithChildren
  '/support': typeof AuthenticatedSupportRoute
  '/vlans': typeof AuthenticatedVlansRoute
  '/': typeof AuthenticatedIndexRoute
  '/status/ports/$port': typeof AuthenticatedStatusPortsPortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/configuration': typeof AuthenticatedConfigurationRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/status': typeof AuthenticatedStatusRouteWithChildren
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/vlans': typeof AuthenticatedVlansRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/status/ports/$port': typeof AuthenticatedStatusPortsPortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backups'
    | '/configuration'
    | '/diagnostics'
    | '/security'
    | '/status'
    | '/support'
    | '/vlans'
    | '/status/ports/$port'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/backups'
    | '/configuration'
    | '/diagnostics'
    | '/security'
    | '/status'
    | '/support'
    | '/vlans'
    | '/'
    | '/status/ports/$port'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/backups'
    | '/_authenticated/configuration'
    | '/_authenticated/diagnostics'
    | '/_authenticated/security'
    | '/_authenticated/status'
    | '/_authenticated/support'
    | '/_authenticated/vlans'
    | '/_authenticated/'
    | '/_authenticated/status/ports/$port'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vlans': {
      id: '/_authenticated/vlans'
      path: '/vlans'
      fullPath: '/vlans'
      preLoaderRoute: typeof AuthenticatedVlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuration': {
      id: '/_authenticated/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof AuthenticatedConfigurationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/status/ports/$port': {
      id: '/_authenticated/status/ports/$port'
      path: '/ports/$port'
      fullPath: '/status/ports/$port'
      preLoaderRoute: typeof AuthenticatedStatusPortsPortRouteImport
      parentRoute: typeof AuthenticatedStatusRoute
    }
  }
}

interface AuthenticatedStatusRouteChildren {
  AuthenticatedStatusPortsPortRoute: typeof AuthenticatedStatusPortsPortRoute
}

const AuthenticatedStatusRouteChildren: AuthenticatedStatusRouteChildren = {
  AuthenticatedStatusPortsPortRoute: AuthenticatedStatusPortsPortRoute,
}

const AuthenticatedStatusRouteWithChildren =
  AuthenticatedStatusRoute._addFileChildren(AuthenticatedStatusRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedConfigurationRoute: typeof AuthenticatedConfigurationRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRouteWithChildren
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedVlansRoute: typeof AuthenticatedVlansRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedConfigurationRoute: AuthenticatedConfigurationRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRouteWithChildren,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedVlansRoute: AuthenticatedVlansRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
